-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE public.tasks (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
 assignee_id UUID REFERENCES public.profiles(id),
 title TEXT NOT NULL,
 description TEXT,
 priority TEXT DEFAULT '中' CHECK (priority IN ('高', '中', '低')),
 status TEXT DEFAULT '待处理' CHECK (status IN ('待处理', '进行中', '已完成')),
 due_date DATE,
 created_at TIMESTAMP DEFAULT NOW(),
 updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_tasks ON public.tasks
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY auth_users_insert_tasks ON public.tasks
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY auth_users_update_tasks ON public.tasks
FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY admins_delete_tasks ON public.tasks
FOR DELETE USING (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.project_milestones (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
 name TEXT NOT NULL,
 completed_at TIMESTAMP,
 created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.project_milestones ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_milestones ON public.project_milestones
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY auth_users_manage_milestones ON public.project_milestones
FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

