-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE public.menus (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 parent_id UUID REFERENCES public.menus(id) ON DELETE CASCADE,
 name TEXT NOT NULL,
 path TEXT NOT NULL,
 icon TEXT,
 sort_order INTEGER DEFAULT 0,
 visible BOOLEAN DEFAULT true,
 permission_code TEXT,
 created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_menus ON public.menus
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY admins_insert_menus ON public.menus
FOR INSERT WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY admins_update_menus ON public.menus
FOR UPDATE USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY admins_delete_menus ON public.menus
FOR DELETE USING (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.role_permissions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 role app_role NOT NULL,
 menu_id UUID REFERENCES public.menus(id) ON DELETE CASCADE NOT NULL,
 UNIQUE (role, menu_id)
);

ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_role_permissions ON public.role_permissions
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY admins_manage_role_permissions ON public.role_permissions
FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

