-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE public.notifications (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
 type TEXT NOT NULL,
 title TEXT NOT NULL,
 content TEXT,
 is_read BOOLEAN DEFAULT false,
 created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_own_notifications ON public.notifications
FOR SELECT USING (user_id = auth.uid());

CREATE POLICY users_update_own_notifications ON public.notifications
FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY admins_insert_notifications ON public.notifications
FOR INSERT WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.system_settings (
 key TEXT PRIMARY KEY,
 value JSONB NOT NULL DEFAULT '{}',
 updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_settings ON public.system_settings
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY admins_manage_settings ON public.system_settings
FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

