-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE shared_memos (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 content TEXT NOT NULL,
 priority TEXT NOT NULL DEFAULT 'medium',
 color TEXT NOT NULL DEFAULT '#fef3c7',
 author TEXT NOT NULL DEFAULT '团队成员',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE shared_memos ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_shared_memos ON shared_memos FOR SELECT USING (true);
CREATE POLICY anon_insert_shared_memos ON shared_memos FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_shared_memos ON shared_memos FOR UPDATE USING (true);
CREATE POLICY anon_delete_shared_memos ON shared_memos FOR DELETE USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.shared_memos;

