-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE public.projects (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL,
 name TEXT NOT NULL,
 stage TEXT,
 start_date DATE,
 end_date DATE,
 status TEXT DEFAULT '进行中',
 extra_data JSONB DEFAULT '{}',
 created_by UUID REFERENCES public.profiles(id),
 created_at TIMESTAMP DEFAULT NOW(),
 updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_projects ON public.projects
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY auth_users_insert_projects ON public.projects
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY auth_users_update_projects ON public.projects
FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY admins_delete_projects ON public.projects
FOR DELETE USING (public.has_role(auth.uid(), 'admin'));

