-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE public.customers (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 industry TEXT,
 cycle_status TEXT CHECK (cycle_status IN ('完成', '服务中', '待跟进')),
 contact_person TEXT,
 phone TEXT,
 address TEXT,
 extra_data JSONB DEFAULT '{}',
 created_by UUID REFERENCES public.profiles(id),
 created_at TIMESTAMP DEFAULT NOW(),
 updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_customers ON public.customers
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY auth_users_insert_customers ON public.customers
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY auth_users_update_customers ON public.customers
FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY admins_delete_customers ON public.customers
FOR DELETE USING (public.has_role(auth.uid(), 'admin'));

