-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE team_notes (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 content TEXT NOT NULL,
 author TEXT NOT NULL DEFAULT '匿名',
 tag TEXT NOT NULL DEFAULT '通知',
 pinned BOOLEAN NOT NULL DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE team_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_team_notes ON team_notes FOR SELECT USING (true);
CREATE POLICY anon_insert_team_notes ON team_notes FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_team_notes ON team_notes FOR UPDATE USING (true);
CREATE POLICY anon_delete_team_notes ON team_notes FOR DELETE USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.team_notes;

