-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE public.agent_configs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 type TEXT NOT NULL CHECK (type IN ('dialog', 'flow', 'collab')),
 system_prompt TEXT,
 model TEXT DEFAULT 'qwen3.6-plus',
 enabled BOOLEAN DEFAULT true,
 config JSONB DEFAULT '{}',
 created_at TIMESTAMP DEFAULT NOW(),
 updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.agent_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_users_select_agents ON public.agent_configs
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY admins_manage_agents ON public.agent_configs
FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.chat_sessions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
 agent_id UUID REFERENCES public.agent_configs(id) ON DELETE SET NULL,
 title TEXT,
 created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_own_sessions ON public.chat_sessions
FOR SELECT USING (user_id = auth.uid());

CREATE POLICY users_insert_own_sessions ON public.chat_sessions
FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY users_update_own_sessions ON public.chat_sessions
FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY users_delete_own_sessions ON public.chat_sessions
FOR DELETE USING (user_id = auth.uid());

CREATE TABLE public.chat_messages (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 session_id UUID REFERENCES public.chat_sessions(id) ON DELETE CASCADE NOT NULL,
 role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
 content TEXT NOT NULL,
 metadata JSONB DEFAULT '{}',
 created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_own_messages ON public.chat_messages
FOR SELECT USING (
 EXISTS (SELECT 1 FROM public.chat_sessions WHERE id = session_id AND user_id = auth.uid())
);

CREATE POLICY users_insert_own_messages ON public.chat_messages
FOR INSERT WITH CHECK (
 EXISTS (SELECT 1 FROM public.chat_sessions WHERE id = session_id AND user_id = auth.uid())
);

